// Code generated by MockGen. DO NOT EDIT.
// Source: member.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/horizoncd/horizon/pkg/models"
)

// MockMemberService is a mock of MemberService interface.
type MockMemberService struct {
	ctrl     *gomock.Controller
	recorder *MockMemberServiceMockRecorder
}

// MockMemberServiceMockRecorder is the mock recorder for MockMemberService.
type MockMemberServiceMockRecorder struct {
	mock *MockMemberService
}

// NewMockMemberService creates a new mock instance.
func NewMockMemberService(ctrl *gomock.Controller) *MockMemberService {
	mock := &MockMemberService{ctrl: ctrl}
	mock.recorder = &MockMemberServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberService) EXPECT() *MockMemberServiceMockRecorder {
	return m.recorder
}

// CreateMember mocks base method.
func (m *MockMemberService) CreateMember(ctx context.Context, postMember models.PostMember) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMember", ctx, postMember)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMember indicates an expected call of CreateMember.
func (mr *MockMemberServiceMockRecorder) CreateMember(ctx, postMember interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMember", reflect.TypeOf((*MockMemberService)(nil).CreateMember), ctx, postMember)
}

// GetMember mocks base method.
func (m *MockMemberService) GetMember(ctx context.Context, memberID uint) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, memberID)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockMemberServiceMockRecorder) GetMember(ctx, memberID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockMemberService)(nil).GetMember), ctx, memberID)
}

// GetMemberOfResource mocks base method.
func (m *MockMemberService) GetMemberOfResource(ctx context.Context, resourceType, resourceID string) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberOfResource", ctx, resourceType, resourceID)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberOfResource indicates an expected call of GetMemberOfResource.
func (mr *MockMemberServiceMockRecorder) GetMemberOfResource(ctx, resourceType, resourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberOfResource", reflect.TypeOf((*MockMemberService)(nil).GetMemberOfResource), ctx, resourceType, resourceID)
}

// ListMember mocks base method.
func (m *MockMemberService) ListMember(ctx context.Context, resourceType string, resourceID uint) ([]models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMember", ctx, resourceType, resourceID)
	ret0, _ := ret[0].([]models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMember indicates an expected call of ListMember.
func (mr *MockMemberServiceMockRecorder) ListMember(ctx, resourceType, resourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMember", reflect.TypeOf((*MockMemberService)(nil).ListMember), ctx, resourceType, resourceID)
}

// RemoveMember mocks base method.
func (m *MockMemberService) RemoveMember(ctx context.Context, memberID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockMemberServiceMockRecorder) RemoveMember(ctx, memberID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockMemberService)(nil).RemoveMember), ctx, memberID)
}

// RequirePermissionEqualOrHigher mocks base method.
func (m *MockMemberService) RequirePermissionEqualOrHigher(ctx context.Context, role, resourceType string, resourceID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequirePermissionEqualOrHigher", ctx, role, resourceType, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequirePermissionEqualOrHigher indicates an expected call of RequirePermissionEqualOrHigher.
func (mr *MockMemberServiceMockRecorder) RequirePermissionEqualOrHigher(ctx, role, resourceType, resourceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequirePermissionEqualOrHigher", reflect.TypeOf((*MockMemberService)(nil).RequirePermissionEqualOrHigher), ctx, role, resourceType, resourceID)
}

// UpdateMember mocks base method.
func (m *MockMemberService) UpdateMember(ctx context.Context, memberID uint, role string) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMember", ctx, memberID, role)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMember indicates an expected call of UpdateMember.
func (mr *MockMemberServiceMockRecorder) UpdateMember(ctx, memberID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMember", reflect.TypeOf((*MockMemberService)(nil).UpdateMember), ctx, memberID, role)
}
