// Code generated by MockGen. DO NOT EDIT.
// Source: controller/template/controller.go

// Package mock_template is a generated GoMock package.
package mock_template

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockController is a mock of Controller interface
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// GetTemplateSchema mocks base method
func (m *MockController) GetTemplateSchema(ctx context.Context, templateName, releaseName string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateSchema", ctx, templateName, releaseName)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateSchema indicates an expected call of GetTemplateSchema
func (mr *MockControllerMockRecorder) GetTemplateSchema(ctx, templateName, releaseName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateSchema", reflect.TypeOf((*MockController)(nil).GetTemplateSchema), ctx, templateName, releaseName)
}
