// Code generated by MockGen. DO NOT EDIT.
// Source: template.go

// Package mock_manager is a generated GoMock package.
package mock_manager

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	q "github.com/horizoncd/horizon/lib/q"
	models "github.com/horizoncd/horizon/pkg/models"
)

// MockTemplateManager is a mock of TemplateManager interface.
type MockTemplateManager struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateManagerMockRecorder
}

// MockTemplateManagerMockRecorder is the mock recorder for MockTemplateManager.
type MockTemplateManagerMockRecorder struct {
	mock *MockTemplateManager
}

// NewMockTemplateManager creates a new mock instance.
func NewMockTemplateManager(ctrl *gomock.Controller) *MockTemplateManager {
	mock := &MockTemplateManager{ctrl: ctrl}
	mock.recorder = &MockTemplateManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateManager) EXPECT() *MockTemplateManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTemplateManager) Create(ctx context.Context, template *models.Template) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, template)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTemplateManagerMockRecorder) Create(ctx, template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTemplateManager)(nil).Create), ctx, template)
}

// DeleteByID mocks base method.
func (m *MockTemplateManager) DeleteByID(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockTemplateManagerMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockTemplateManager)(nil).DeleteByID), ctx, id)
}

// GetByID mocks base method.
func (m *MockTemplateManager) GetByID(ctx context.Context, id uint) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTemplateManagerMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTemplateManager)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockTemplateManager) GetByName(ctx context.Context, name string) (*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTemplateManagerMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTemplateManager)(nil).GetByName), ctx, name)
}

// GetRefOfApplication mocks base method.
func (m *MockTemplateManager) GetRefOfApplication(ctx context.Context, id uint) ([]*models.Application, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefOfApplication", ctx, id)
	ret0, _ := ret[0].([]*models.Application)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRefOfApplication indicates an expected call of GetRefOfApplication.
func (mr *MockTemplateManagerMockRecorder) GetRefOfApplication(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefOfApplication", reflect.TypeOf((*MockTemplateManager)(nil).GetRefOfApplication), ctx, id)
}

// GetRefOfCluster mocks base method.
func (m *MockTemplateManager) GetRefOfCluster(ctx context.Context, id uint) ([]*models.Cluster, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefOfCluster", ctx, id)
	ret0, _ := ret[0].([]*models.Cluster)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRefOfCluster indicates an expected call of GetRefOfCluster.
func (mr *MockTemplateManagerMockRecorder) GetRefOfCluster(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefOfCluster", reflect.TypeOf((*MockTemplateManager)(nil).GetRefOfCluster), ctx, id)
}

// ListByGroupID mocks base method.
func (m *MockTemplateManager) ListByGroupID(ctx context.Context, groupID uint) ([]*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGroupID", ctx, groupID)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByGroupID indicates an expected call of ListByGroupID.
func (mr *MockTemplateManagerMockRecorder) ListByGroupID(ctx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGroupID", reflect.TypeOf((*MockTemplateManager)(nil).ListByGroupID), ctx, groupID)
}

// ListByGroupIDs mocks base method.
func (m *MockTemplateManager) ListByGroupIDs(ctx context.Context, ids []uint) ([]*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByGroupIDs", ctx, ids)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByGroupIDs indicates an expected call of ListByGroupIDs.
func (mr *MockTemplateManagerMockRecorder) ListByGroupIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByGroupIDs", reflect.TypeOf((*MockTemplateManager)(nil).ListByGroupIDs), ctx, ids)
}

// ListByIDs mocks base method.
func (m *MockTemplateManager) ListByIDs(ctx context.Context, ids []uint) ([]*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockTemplateManagerMockRecorder) ListByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockTemplateManager)(nil).ListByIDs), ctx, ids)
}

// ListTemplate mocks base method.
func (m *MockTemplateManager) ListTemplate(ctx context.Context) ([]*models.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplate", ctx)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplate indicates an expected call of ListTemplate.
func (mr *MockTemplateManagerMockRecorder) ListTemplate(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplate", reflect.TypeOf((*MockTemplateManager)(nil).ListTemplate), ctx)
}

// ListV2 mocks base method.
func (m *MockTemplateManager) ListV2(ctx context.Context, query *q.Query, groupIDs ...uint) ([]*models.Template, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, query}
	for _, a := range groupIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListV2", varargs...)
	ret0, _ := ret[0].([]*models.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListV2 indicates an expected call of ListV2.
func (mr *MockTemplateManagerMockRecorder) ListV2(ctx, query interface{}, groupIDs ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, query}, groupIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListV2", reflect.TypeOf((*MockTemplateManager)(nil).ListV2), varargs...)
}

// UpdateByID mocks base method.
func (m *MockTemplateManager) UpdateByID(ctx context.Context, id uint, template *models.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockTemplateManagerMockRecorder) UpdateByID(ctx, id, template interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockTemplateManager)(nil).UpdateByID), ctx, id, template)
}
