openapi: 3.0.1
info:
  title: Horizon Cluster Front
  version: 2.0.0
servers:
  - url: 'http://localhost:8080/'
paths:
  /apis/front/v2/clusters/{clusterName}:
    get:
      tags:
        - cluster
      description: get cluster by name
      operationId: getClusterByName
      parameters:
        - name: clusterName
          in: path
          description: name of cluster
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: "#/components/schemas/GetClusterByNameResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/front/v2/clusters/searchclusters?filter={filter}&userID={userID}&environment={environment}&template={template}&templateRelease={templateRelease}&applicationID={applicationID}&tagSelector={tagSelector}&pageNumber={pageNumber}&pageSize={pageSize}:
    get:
      tags:
        - cluster
      description: search clusters by environment, template, tag, application and fuzzy name
      operationId: searchClusters
      parameters:
        - $ref: 'common.yaml#/components/parameters/filter'
        - $ref: 'common.yaml#/components/parameters/userID'
        - $ref: 'common.yaml#/components/parameters/environment'
        - $ref: 'common.yaml#/components/parameters/template'
        - $ref: 'common.yaml#/components/parameters/templateRelease'
        - $ref: 'common.yaml#/components/parameters/applicationID'
        - $ref: 'common.yaml#/components/parameters/tagSelector'
        - $ref: 'common.yaml#/components/parameters/pageNumber'
        - $ref: 'common.yaml#/components/parameters/pageSize'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/listClustersResp'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"

  /apis/front/v2/clusters/searchmyclusters?filter={filter}&userID={userID}&environment={environment}&template={template}&templateRelease={templateRelease}&applicationID={applicationID}&tagSelector={tagSelector}&pageNumber={pageNumber}&pageSize={pageSize}:
    get:
      tags:
        - cluster
      description: search my clusters by environment, template, tag, application and fuzzy name
      operationId: searchMyClusters
      parameters:
        - $ref: 'common.yaml#/components/parameters/filter'
        - $ref: 'common.yaml#/components/parameters/environment'
        - $ref: 'common.yaml#/components/parameters/template'
        - $ref: 'common.yaml#/components/parameters/templateRelease'
        - $ref: 'common.yaml#/components/parameters/applicationID'
        - $ref: 'common.yaml#/components/parameters/tagSelector'
        - $ref: 'common.yaml#/components/parameters/pageNumber'
        - $ref: 'common.yaml#/components/parameters/pageSize'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    $ref: '#/components/schemas/listClustersResp'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/Error"
components:
  schemas:
    GetClusterByNameResponse:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        template:
          $ref: '#/components/schemas/template'
        git:
          $ref: '#/components/schemas/git'
        createdAt:
          $ref: '#/components/schemas/createdAt'
        updatedAt:
          $ref: '#/components/schemas/updatedAt'
        fullPath:
          $ref: '#/components/schemas/fullPath'
    listClustersResp:
      type: object
      properties:
        total:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/cluster'
    cluster:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'
        name:
          $ref: '#/components/schemas/name'
        description:
          $ref: '#/components/schemas/description'
        scope:
          $ref: '#/components/schemas/scope'
        template:
          $ref: '#/components/schemas/template'
        git:
          $ref: '#/components/schemas/git'
        tags:
          $ref: '#/components/schemas/tags'
        createdAt:
          $ref: '#/components/schemas/createdAt'
        updatedAt:
          $ref: '#/components/schemas/updatedAt'
        fullPath:
          $ref: '#/components/schemas/fullPath'
        fullName:
          $ref: '#/components/schemas/fullName'
    id:
      type: integer
      format: int64
      description: id of cluster
    name:
      type: string
      description: name of cluster
    description:
      type: string
      description: description of cluster
    environment:
      type: string
      description: name of environment
    region:
      type: string
      description: name of region
    regionDisplayName:
      type: string
      description: display name of region
    scope:
      type: object
      description: scope of cluster, including environment and region
      properties:
        environment:
          $ref: '#/components/schemas/environment'
        region:
          $ref: '#/components/schemas/region'
        regionDisplayName:
          $ref: '#/components/schemas/regionDisplayName'
    template:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/templateName'
        release:
          $ref: '#/components/schemas/templateRelease'
    templateName:
      type: string
      description: name of template
    templateRelease:
      type: string
      description: release version of template
    git:
      type: object
      properties:
        sshURL:
          $ref: '#/components/schemas/sshURL'
        httpURL:
          $ref: '#/components/schemas/httpURL'
    sshURL:
      type: string
      description: ssh url of git repository
    httpURL:
      type: string
      description: http url of git repository
    tags:
      type: array
      items:
        $ref: '#/components/schemas/tag'
    tag:
      type: object
      description: tag of cluster
      properties:
        key:
          $ref: '#/components/schemas/key'
        value:
          $ref: '#/components/schemas/value'
    key:
      type: string
    value:
      type: string
    createdAt:
      type: string
      description: creation time of cluster, contains the timezone
    updatedAt:
      type: string
      description: creation time of cluster, contains the timezone
    fullName:
      type: string
      description: full name of cluster
    fullPath:
      type: string
      description: full path of cluster