name: horizon-core
serviceType: deployment
containers:
  - name: core
    dev:
      gitUrl: ""
      image: horizoncd/go-dlv:1.0
      shell: ""
      workDir: ""
      storageClass: ""
      persistentVolumeDirs: []
      command:
        run:
          - .nocalhost/run.sh
        debug:
          - .nocalhost/debug.sh
      debug:
        remoteDebugPort: 9009
      hotReload: false
      sync:
        type: "send"
        mode: "pattern"
        filePattern: []
        ignoreFilePattern:
          - "./build"
          - "./db"
          - "./mock"
          - "./openapi"
      env: []
      portForward: []
