// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/cluster/registry/factory/factory.go

// Package mock_factory is a generated GoMock package.
package mock_factory

import (
	context "context"
	registry "g.hz.netease.com/horizon/pkg/cluster/registry"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFactory is a mock of Factory interface
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// GetByHarborConfig mocks base method
func (m *MockFactory) GetByHarborConfig(ctx context.Context, harbor *registry.HarborConfig) registry.Registry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHarborConfig", ctx, harbor)
	ret0, _ := ret[0].(registry.Registry)
	return ret0
}

// GetByHarborConfig indicates an expected call of GetByHarborConfig
func (mr *MockFactoryMockRecorder) GetByHarborConfig(ctx, harbor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHarborConfig", reflect.TypeOf((*MockFactory)(nil).GetByHarborConfig), ctx, harbor)
}
