// Code generated by MockGen. DO NOT EDIT.
// Source: legacycd.go

// Package mock_cd is a generated GoMock package.
package mock_cd

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cd "github.com/horizoncd/horizon/pkg/cd"
)

// MockLegacyCD is a mock of LegacyCD interface.
type MockLegacyCD struct {
	ctrl     *gomock.Controller
	recorder *MockLegacyCDMockRecorder
}

// MockLegacyCDMockRecorder is the mock recorder for MockLegacyCD.
type MockLegacyCDMockRecorder struct {
	mock *MockLegacyCD
}

// NewMockLegacyCD creates a new mock instance.
func NewMockLegacyCD(ctrl *gomock.Controller) *MockLegacyCD {
	mock := &MockLegacyCD{ctrl: ctrl}
	mock.recorder = &MockLegacyCDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLegacyCD) EXPECT() *MockLegacyCDMockRecorder {
	return m.recorder
}

// CreateCluster mocks base method.
func (m *MockLegacyCD) CreateCluster(ctx context.Context, params *cd.CreateClusterParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCluster", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockLegacyCDMockRecorder) CreateCluster(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockLegacyCD)(nil).CreateCluster), ctx, params)
}

// DeleteCluster mocks base method.
func (m *MockLegacyCD) DeleteCluster(ctx context.Context, params *cd.DeleteClusterParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockLegacyCDMockRecorder) DeleteCluster(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockLegacyCD)(nil).DeleteCluster), ctx, params)
}

// DeployCluster mocks base method.
func (m *MockLegacyCD) DeployCluster(ctx context.Context, params *cd.DeployClusterParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployCluster", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeployCluster indicates an expected call of DeployCluster.
func (mr *MockLegacyCDMockRecorder) DeployCluster(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployCluster", reflect.TypeOf((*MockLegacyCD)(nil).DeployCluster), ctx, params)
}

// GetClusterState mocks base method.
func (m *MockLegacyCD) GetClusterState(ctx context.Context, params *cd.GetClusterStateV2Params) (*cd.ClusterStateV2, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterState", ctx, params)
	ret0, _ := ret[0].(*cd.ClusterStateV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterState indicates an expected call of GetClusterState.
func (mr *MockLegacyCDMockRecorder) GetClusterState(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterState", reflect.TypeOf((*MockLegacyCD)(nil).GetClusterState), ctx, params)
}

// GetClusterStateV1 mocks base method.
func (m *MockLegacyCD) GetClusterStateV1(ctx context.Context, params *cd.GetClusterStateParams) (*cd.ClusterState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterStateV1", ctx, params)
	ret0, _ := ret[0].(*cd.ClusterState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterStateV1 indicates an expected call of GetClusterStateV1.
func (mr *MockLegacyCDMockRecorder) GetClusterStateV1(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterStateV1", reflect.TypeOf((*MockLegacyCD)(nil).GetClusterStateV1), ctx, params)
}

// GetPodEvents mocks base method.
func (m *MockLegacyCD) GetPodEvents(ctx context.Context, params *cd.GetPodEventsParams) ([]cd.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPodEvents", ctx, params)
	ret0, _ := ret[0].([]cd.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPodEvents indicates an expected call of GetPodEvents.
func (mr *MockLegacyCDMockRecorder) GetPodEvents(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPodEvents", reflect.TypeOf((*MockLegacyCD)(nil).GetPodEvents), ctx, params)
}

// GetResourceTree mocks base method.
func (m *MockLegacyCD) GetResourceTree(ctx context.Context, params *cd.GetResourceTreeParams) ([]cd.ResourceNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceTree", ctx, params)
	ret0, _ := ret[0].([]cd.ResourceNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceTree indicates an expected call of GetResourceTree.
func (mr *MockLegacyCDMockRecorder) GetResourceTree(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceTree", reflect.TypeOf((*MockLegacyCD)(nil).GetResourceTree), ctx, params)
}

// GetStep mocks base method.
func (m *MockLegacyCD) GetStep(ctx context.Context, params *cd.GetStepParams) (*cd.Step, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStep", ctx, params)
	ret0, _ := ret[0].(*cd.Step)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStep indicates an expected call of GetStep.
func (mr *MockLegacyCDMockRecorder) GetStep(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStep", reflect.TypeOf((*MockLegacyCD)(nil).GetStep), ctx, params)
}
