// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/service/template/template.go

// Package mock_template is a generated GoMock package.
package mock_template

import (
	context "context"
	template "g.hz.netease.com/horizon/pkg/service/template"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockInterface is a mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// GetTemplateSchema mocks base method
func (m *MockInterface) GetTemplateSchema(ctx context.Context, templateName, releaseName string) (*template.Schemas, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateSchema", ctx, templateName, releaseName)
	ret0, _ := ret[0].(*template.Schemas)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateSchema indicates an expected call of GetTemplateSchema
func (mr *MockInterfaceMockRecorder) GetTemplateSchema(ctx, templateName, releaseName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateSchema", reflect.TypeOf((*MockInterface)(nil).GetTemplateSchema), ctx, templateName, releaseName)
}
